# Generated by Django 4.1.7 on 2023-03-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdo',
            name='color_bg',
            field=models.CharField(blank=True, default='fff', max_length=6),
        ),
    ]
